# Generated by Django 4.1.7 on 2023-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date_cl', models.CharField(max_length=100)),
                ('place', models.TextField()),
                ('fecha_utc', models.TextField()),
                ('earthquake_latitude', models.TextField()),
                ('earthquake_longitude', models.TextField()),
                ('earthquake_deep', models.TextField()),
                ('magnitude', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'sismos',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
